# Generated by Django 3.0.5 on 2020-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='filepath',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
